### ISSUE TITLE
add support for git clone

### ISSUE THREAD

**Issue by kilip** [kilip/ansible-role-workstation#6]
support for git clone with this vars:
```yaml
ws_git_clone:
  - repo: git@gihub.com:username/repo.git
    dest: /some/dir
```
