### ISSUE TITLE
fix sync repo tasks

### ISSUE THREAD

**Issue by kilip** [kilip/ansible-role-workstation#9]
disable ```Host Key Verification``` git during clone:
```yaml
- name: Sync git dotfiles repo
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "main"
    single_branch: true
    key_file: "{{ ws_user_home }}/.ssh/workstation"
    accept_newhostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"
  with_items: "{{ ws_sync_repo }}"
  loop_control:
    label: "{{ item.dest | basename }}"
  become: true
  become_user: "{{ ws_user }}"
```
